### ISSUE TITLE
VTOL.exe not opening

### ISSUE THREAD

**Issue by Git-North** [BigSpice/VTOL#15]
**Describe the bug**

**To Reproduce**
1. Use the installer
2. Set the installation path inside Titanfall folder
3. Open the VTOL.exe
4. Press "repair/install northstar"
5. Crash
6. App doesn't open again

**Expected behaviour**
To app to open

**Desktop:**
 - OS: [Windows 10]

**Additional context**
we tried installing it outside the game folder aswell
And then an entirely different disc
Non of them worked after the first crash occurred
We tried repairing and uninstalling re installing trying a different version uninstalling from the control panel reinstalling the net framework
Non worked

Also when we try running it appears to be doing _something_, in the background

**Comment by Git-North** [comment]
filepath(s): g://titanfall2/R2Northstar/__Launcher/VTOL
g://juicy/vtol
(default path)c://program files (x86)/juicy/vtol

**Comment by ConnorDoesDev** [comment]
you have to set your filepath to your titanfall exe

**Comment by ConnorDoesDev** [comment]
could you send me a screenshot of your set path

**Comment by BigSpice** [comment]
And ensure to install this in the Program files x86 folder
The defualt. 
This can and will cause dependency issues if its not installed like any program.

**Comment by MysteriousRSA** [comment]
@Git-North 

Have you tried uninstalling VTOL completely, installing a newer version into the default directory and just setting Titanfall path fr there?

**Comment by MysteriousRSA** [comment]
Also, if possible, please provide screenshots of Titanfall 2's install location and a full path to it.

**Comment by BigSpice** [comment]
Closed due to finding the issue and inactivity.
