### ISSUE TITLE
Mod Section Error

### ISSUE THREAD

**Issue by MysteriousRSA** [BigSpice/VTOL#19]

**Comment by MysteriousRSA** [comment]
**Describe the bug**
Clicking on the MODS menu on the left side panel causes an error to pop up

The logs just say

``
No inactive Mods Found
2022/02/24 18:45:34
Sequence contains no elements
``

Fatal Error Occured, Please Check Logs!
2022/02/24 18:45:34


This issues doesn't prevent the use of the mod section, it just is a bit strange

**To Reproduce**
Steps to reproduce the behavior:
1. Click on the Mods section in the left side panel

**Expected behavior**
A Mod List showing

**Screenshots**
![image](https://user-images.githubusercontent.com/45333346/155568837-9cbd7c5b-a8ec-40f7-901d-4fa341982857.png)
![image](https://user-images.githubusercontent.com/45333346/155568871-d680d29f-9fa6-4356-820d-dcc2c205699d.png)
![image](https://user-images.githubusercontent.com/45333346/155568947-9de83406-48d0-4bfc-850a-c040858fc8df.png)



**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context**

**Comment by BigSpice** [comment]
on it

**Comment by BigSpice** [comment]
Bug was empty folder generated by Viper.
