### ISSUE TITLE
Fatal Error on attempting to update Northstar.

### ISSUE THREAD

**Issue by drearyplane8** [BigSpice/VTOL#34]
After having installed VTOL and found my TF2 folder, pressing Update/Repair Northstar causes a fatal error

**To Reproduce**
1. Launch VTOL
2. Click on Update/Repair Northstar
4. See Fatal Error Occured.

Checking the logs shows: 

`Release Parsed! found -https://github.com/R2Northstar/Northstar/releases/download/v1.7.0/Northstar.release.v1.7.0.zip
01/05/2022 12:13:00

Backing up arg files
01/05/2022 12:13:03
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at VTOL.MainWindow.Install_NS_METHOD() in D:\Development Northstar AmVCX C++ branch 19023 ID 44\VTOL\MainWindow.xaml.cs:line 2256

Fatal Error Occured, Please Check Logs!
01/05/2022 12:13:03`

**Expected behavior**
VTOL updates my Northstar.

**Screenshots**
![image](https://user-images.githubusercontent.com/69673673/166143590-75a7cb82-6694-4752-b134-07207c7e9acf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 21H2

**Additional context**
VTOL asks for admin when opening, I said yes.
I have tried un-and-reinstalling multiple times.
Northstar works fine normally.
Mods failed to install from the mod store.

**Comment by BigSpice** [comment]
Hey @drearyplane8. 
Spent the last few hours investigating and fixing the issue.
1.2.2 release is in final test and has been distributed. 
Please sit tight as the release is finalized.

**Comment by drearyplane8** [comment]
Thank you!

**Comment by BigSpice** [comment]
Please re-comment if the issue has been solved :D

**Comment by drearyplane8** [comment]
Sorry, was away from my PC for a bit. Works a treat.
