### ISSUE TITLE
Consider additionally supporting downloading Northstar from Thunderstore

### ISSUE THREAD

**Issue by GeckoEidechse** [BigSpice/VTOL#42]
**What feature would you like added?**
VTOL currently downloads Northstar from GitHub but we also upload Northstar to Thunderstore as well. In fact Thunderstore version [gets auto-upload by CI on release](https://github.com/R2Northstar/Northstar/blob/main/.github/workflows/build.yml#L132-L192).

**Why should this feature be added?**
The reason for supporting Thunderstore Northstar download is a bit of selfish one. We're [planning to also auto-upload release candidates to their own package on Thunderstore](https://github.com/R2Northstar/Northstar/issues/309#issuecomment-1180652588) (`NorthstarReleaseCandidate` vs `Northstar`). By supporting Thunderstore download, it would be really easy to then add support for selecting a release channel in VTOL. So player could then pick whether they want to be in "stable" or "release candidate" channel. "stable" would obviously be the default while "release candidate" would have to be changed to manually.
That way when we enable auto-upload release candidates we can then point playtesters to just select "release candidate" channel in VTOL to playtest the newest release candidates which is way easier for them to do compared to having to manually download a release-candidate from GitHub actions every time we do a new one.

**Additional Info**
I'd still keep support for GitHub and then have an option to select download source. Whether GitHub or Thunderstore should be the default is a decision I'll leave up to you. Currently it makes no difference :P

**Comment by BigSpice** [comment]
I agree with this, 
i can work in UI to make a choice between the 2 sources.
But how do you plan to distribute the Patch notes?.

**Comment by GeckoEidechse** [comment]
Patch notes are will still only be on GitHub for the foreseeable future. ^^

**Comment by BigSpice** [comment]
Done in ver 2.0.0
