### ISSUE TITLE
cant open vtol

### ISSUE THREAD

**Issue by EngineerKermit** [BigSpice/VTOL#45]
![unknown](https://user-images.githubusercontent.com/113150524/189246897-695c1e45-326b-44ce-91fe-dbdf1f690c67.png)
so i have everything installed even though i still get the error, am not all that tech savy, so just curious if you got a fix for this

**Comment by BigSpice** [comment]
please

![image](https://user-images.githubusercontent.com/23240514/189257753-e43f0d27-29ce-4206-be6b-4aa12995acb2.png)

Read through all documentation and pages next time.

**Comment by EngineerKermit** [comment]
i have done all of this already, i still get the same error for some reason

**Comment by EngineerKermit** [comment]
thanks, got it all working, missread some stuff and all
