### ISSUE TITLE
you must install or update .net

### ISSUE THREAD

**Issue by xveteran** [BigSpice/VTOL#46]
keep getting this error message, I have reinstalled multiple times 
![image](https://user-images.githubusercontent.com/66324601/189327363-234012a4-4de1-460a-9883-f22bd8295026.png)

**Comment by BigSpice** [comment]
no
you havent
![image](https://user-images.githubusercontent.com/23240514/189333428-a5a1f1b3-5946-417a-a464-0791cb88d10b.png)

**Comment by BigSpice** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.8-windows-x64-installer
