### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by ConnorDoesDev** [BigSpice/VTOL#47]
Hello, sorry for being inactive, I've thought about adding native MacOS support for this? 
A few people like running northstar servers on MacOS.

**Comment by ConnorDoesDev** [comment]
We don't need to port the whole codebase, maybe just the dedicated server tools.

**Comment by BigSpice** [comment]
Not too sure how I'd go about that, let me look into it.

**Comment by GeckoEidechse** [comment]
> A few people like running northstar servers on MacOS.

Hol' up that's actually a thing? o_O
I assume they use Docker under the hood, i.e. virtualised Linux?

If your focus is servers, [`papa`](https://github.com/AnActualEmerald/papa) might get the job done. It doesn't have a dedicated MacOS release but you should be able to just install Rust toolchain and then run `cargo install papa`.

Given MacOS' move to ARM and the lack of ability to even run Northstar natively on amd64 I don't think a MacOS port is of any use unless the number of potential users is in the tens to hundreds.

**Comment by BigSpice** [comment]
true

**Comment by BigSpice** [comment]
i Have looked into it
we would have to migrate to .NET MAUI and that platform has its own issues.
