### ISSUE TITLE
Could not find VTOL_DATA\Settings

### ISSUE THREAD

**Issue by ChaosSpindash** [BigSpice/VTOL#48]
**Describe the bug**
VTOL.exe won't start. Shows up briefly on Task Manager then disappears.
Event Viewer shows that it threw a .NET Runtime Error (System.IO.FileNotFoundException), stating that it could not find VTOL_DATA\Settings in the Documents folder.
Occurs with both regular install and portable version.

**To Reproduce**
1. Install VTOL to default directory OR use the portable EXE version.
2. Start VTOL.

**Expected behavior**
VTOL should start up as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/29288731/190458683-20b9445b-b199-481a-bdd0-b97c05f164a5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Version [21H2]

**Additional context**
For some reason the 2.0.1 update kept failing, so I wanted to go for a new install. I noticed that Windows listed two concurrent versions of VTOL being installed - 1.2.6 and 2.0.1. I uninstalled both and reinstalled the newest version. That's when I encountered the issue.

**Comment by BigSpice** [comment]
hey, should be sorted now
