### ISSUE TITLE
Application crashing some seconds after opening it

### ISSUE THREAD

**Issue by Katzenwerfer** [BigSpice/VTOL#55]
I installed the application for the first time in my computer. The installation process worked successfully.
When I open the app it prompts me that Northstar is autoinstalling, which after it finishes the application crashes. Opening it again prompts that autoinstallation process is executing, and the same behavior repeats endlessly.

I assume this is a similar issue to #52.

1. Open the VTOL application

My operating system is Windows 11 Home 22H2

**Comment by BigSpice** [comment]
Run as admin

**Comment by BigSpice** [comment]
@Katzenwerfer
