### ISSUE TITLE
Latest Update I cannot edit launch arguments

### ISSUE THREAD

**Issue by meechgalhuquot** [BigSpice/VTOL#9]
As title says, I cannot edit the launch arguments. I add -noborder -windowed to make the game run in Bordered Windowless mode and now I cannot add it

**Comment by BigSpice** [comment]
Hey @meechgalhuquot , Apologies for that,
I can see the UI for 1.1.9 is somhow not allowing editing. Fixing it now.
Fix will be out with 1.2.0.
Please alos check these to prevent and overwrite next time.
![image](https://user-images.githubusercontent.com/23240514/152694846-be67dd78-94b1-4213-bcfd-cfbac9939baa.png)
